### PR TITLE
Support serving gzipped files

### PR DESCRIPTION
**Pull request by i80and**
This patch adds a `serve_gzip` configuration option that allows serving `file.gz` as `file` with `Content-Encoding: gzip` if the client advertises that it accepts said encoding.

To keep it simple, `serve_gzip` is conservative, and does not serve gzip at all if `Accept-Encoding: gzip` specifies a qvalue[[1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3)] (because q=0 is possible). If desired, I can implement qvalue parsing.

`Vary: Accept-Encoding` is currently added unconditionally, but it might make sense to only add it if the `serve_gzip` configuration option is given.

EDIT: Optional second commit adds support for serving Brotli files as well.

### CODE REVIEW

**Comment by reyk** [comment]
Thanks for the diff. We carefully have to consider if we'd want to include such functionality.

**Comment by i80and** [comment]
Noted. I was worried this would be considered featuritis, so absolutely don't take this if you're not comfortable with it.

**Comment by Neustradamus** [comment]
@i80and: Why have you closed your PR?

**Comment by i80and** [comment]
@Neustradamus If you need this feature, I believe the `gzip-static` config stanza now exists: https://man.openbsd.org/httpd.conf#gzip-static

**Pull request closed without merging**
